### ISSUE TITLE
Build and deploy on github (or internal gitea)

### ISSUE THREAD

**Issue by erikfrojdh** [slsdetectorgroup/slsDetectorPackage#1154]

**Comment by JamesOHeaDLS** [comment]
Hi @erikfrojdh 

The way we have done pypi deployment on GitHub at DLS is as follows:

Have a _dist.yml with

```
on:
  workflow_call:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Need this to get version number from last tag
          fetch-depth: 0

      - name: Build sdist and wheel
        run: >
          export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct) &&
          pipx run build

      - name: Upload sdist and wheel as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

      - name: Check for packaging errors
        run: pipx run twine check --strict dist/*

      - name: Install produced wheel
        uses: ./.github/actions/install_requirements
        with:
          pip-install: dist/*.whl

      - name: Test module --version works using the installed wheel
        # If more than one module in src/ replace with module name to test
        run: python -m $(ls --hide='*.egg-info' src | head -1) --version
```

Have a _pypi.yml with

```
on:
  workflow_call:

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish to PyPI using trusted publishing
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: false
```

and referencing these jobs within ci.yml

```
  dist:
    needs: check
    if: needs.check.outputs.branch-pr == ''
    uses: ./.github/workflows/_dist.yml
  
  pypi:
    if: github.ref_type == 'tag'
    needs: dist
    uses: ./.github/workflows/_pypi.yml
    permissions:
      id-token: write
```

James
